[package]
name = "wallet-actor-system"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"
exclude = ["/bindings", "/api-wrapper"]

[dependencies]
tokio = { version = "1.3", features = ["full"] }
once_cell = "1.5.0"
iota-wallet = { path = "../../../wallet.rs-temp", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator", "participation"] }
#iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "32c9667abca5635b9267bc454b1b5cfe6392af92", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator"] }
serde_json = "1.0"
riker = "0.4"
serde = "1.0"
iota-client = { git = "https://github.com/iotaledger/iota.rs", rev = "d99eedf4f5a0d45edacf05bafb7bceefa166d01f" }
log = "0.4"

[dev-dependencies]
futures = "0.3"
