[package]
name = "wallet-actor-system"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"
exclude = ["/bindings", "/api-wrapper"]

[dependencies]
tokio = { version = "1.3", features = ["full"] }
once_cell = "1.5.0"
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", rev = "440e7e593acdf51c3d0b502c0a276481a26d71e3", default-features = false, features = ["stronghold", "ledger-nano", "ledger-nano-simulator"] }
serde_json = "1.0"
riker = "0.4"
serde = "1.0"
iota-client = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
log = "0.4"

[dev-dependencies]
futures = "0.3"
